name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------- Backend ----------------
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/todo-backend:latest
          build-args: |
            NODE_ENV=production
          target: production

      # ---------------- Frontend ----------------
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/todo-frontend:latest
          build-args: |
            NODE_ENV=production
          target: production

      - name: Deployment summary
        run: |
          echo "✅ Production images pushed to Docker Hub!"
          echo "Backend: ${{ vars.DOCKER_USERNAME }}/todo-backend:latest"
          echo "Frontend: ${{ vars.DOCKER_USERNAME }}/todo-frontend:latest"
